const ShopActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH__COLLECTIONS_FAILURE: 'FETCH__COLLECTIONS_FAILURE',
};

export default ShopActionTypes;
